# Generated by Django 3.1.2 on 2020-10-29 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0005_auto_20201028_2324'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Categorie',
        ),
    ]
