# Generated by Django 3.1.2 on 2020-11-08 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0007_auto_20201108_1407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Categories',
            new_name='category',
        ),
    ]
